version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: friday
    labels:
      - dependencies
      - go
      - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
    labels:
      - dependencies
      - github-actions
      - patch
