version: "2"
run:
  issues-exit-code: 0
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - gocritic
    - gocyclo
    - godox
    - makezero
    - misspell
    - unconvert
  settings:
    govet:
      disable:
        - stdmethods
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
