version: 2

project_name: fget

before:
  hooks:
    - go mod download all

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X "{{ .ModulePath }}/version.GitCommit={{ .ShortCommit }}"
      - -X "{{ .ModulePath }}/version.Version={{ .Version }}"
      - -X "{{ .ModulePath }}/version.BuiltBy=goreleaser"

archives:
  - files:
      - none*

changelog:
  disable: true

release:
  disable: true
